apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinks-kubernetes-demo-apache2-hello-web

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: jenkinks-kubernetes-demo-apache2-hello-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkinks-kubernetes-demo-apache2-hello-web
    spec:
      containers:
      - image: gcr.io/tcs-cloud-devops/demo-apache2-kube:latest
        imagePullPolicy: IfNotPresent
        name: apache2-sample
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkinks-kubernetes-demo-apache2-hello-web
  name: jenkinks-kubernetes-demo-apache2-hello-web
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32292
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: jenkinks-kubernetes-demo-apache2-hello-web
  sessionAffinity: None
  type: LoadBalancer

