apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-jenkinks-apache2-hello-web
  name: demo-jenkinks-apache2-hello-web
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32292
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-jenkinks-apache2-hello-web
  sessionAffinity: None
  type: LoadBalancer
